# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node.

name: Betalife CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    services:
      postgres:
        image: postgres:11.6-alpine
        env:
          POSTGRES_USER: test-user
          POSTGRES_DB: betalifeTestDB
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

        env:
          CI: true
          DATABASE_URL: 'postgres://test-user@localhost:5432/betalifeTestDB'
          ACCESS_TOKEN_SECRET: '|[%$_g:c@K7J#5;WI`Dk`6t/ndEg#AAnibO+.eIK-g{l>Rrwx-c+eW02%C `dFU/'
